# Generated by Django 6.0.5 on 2026-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealingredient",
            name="quantity_used_g",
            field=models.FloatField(null=True),
        ),
    ]
