# Generated by Django 6.0.5 on 2026-05-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meals", "0003_alter_mealingredient_quantity_used_g"),
    ]

    operations = [
        migrations.AddField(
            model_name="meal",
            name="name",
            field=models.CharField(default="Unnamed Meal", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="mealingredient",
            name="quantity_used_g",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
