# Generated by Django 6.0.5 on 2026-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MasterItemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(blank=True, max_length=255)),
                ("potassium_mg", models.FloatField(null=True)),
                ("protein_g", models.FloatField(null=True)),
                ("total_sugar_g", models.FloatField(null=True)),
                ("added_sugar_g", models.FloatField(null=True)),
                ("sodium_g", models.FloatField(null=True)),
                ("quantity_g", models.FloatField(null=True)),
                ("calories", models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PantryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_g", models.FloatField(null=True)),
            ],
        ),
    ]
