# Generated by Django 6.0.5 on 2026-06-07 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="pantryitem",
            name="inventory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.inventory"
            ),
        ),
        migrations.AddField(
            model_name="pantryitem",
            name="master_item_info",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.masteriteminfo",
            ),
        ),
    ]
