# Generated by Django 6.0.5 on 2026-05-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="masteriteminfo",
            name="potassium_mg",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="masteriteminfo",
            name="protein_g",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="masteriteminfo",
            name="quantity_g",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="masteriteminfo",
            name="sodium_g",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="masteriteminfo",
            name="sugar_g",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="pantryitem",
            name="quantity_g",
            field=models.FloatField(null=True),
        ),
    ]
