# Generated by Django 6.0.5 on 2026-05-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_masteriteminfo_potassium_mg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="masteriteminfo",
            name="calories",
            field=models.FloatField(null=True),
        ),
    ]
