# Generated by Django 6.0.5 on 2026-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_masteriteminfo_calories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="masteriteminfo",
            old_name="sugar_g",
            new_name="added_sugar_g",
        ),
        migrations.AddField(
            model_name="masteriteminfo",
            name="total_sugar_g",
            field=models.FloatField(null=True),
        ),
    ]
